CREATE DATABASE IF NOT EXISTS gestione_buste_paga;

USE gestione_buste_paga;

CREATE TABLE IF NOT EXISTS dipendenti (
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    codice_fiscale VARCHAR(16) PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    cognome VARCHAR(45) NOT NULL,
    data_di_assunzione DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS RAL (
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    codice_fiscale VARCHAR(16),
    anno INT,
    importo FLOAT NOT NULL,
    PRIMARY KEY (codice_fiscale, anno),
    FOREIGN KEY (codice_fiscale) REFERENCES dipendenti(codice_fiscale)
);

CREATE TABLE IF NOT EXISTS RAN (
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    codice_fiscale VARCHAR(16),
    anno INT,
    importo FLOAT NOT NULL,
    PRIMARY KEY (codice_fiscale, anno),
    FOREIGN KEY (codice_fiscale) REFERENCES dipendenti(codice_fiscale)
);

CREATE TABLE IF NOT EXISTS busta_paga (
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    id INT AUTO_INCREMENT,
    stipendio_lordo FLOAT NOT NULL,
    stipendio_netto FLOAT NOT NULL,
    data_emissione DATE NOT NULL,
    codice_fiscale VARCHAR(16),
    PRIMARY KEY (id),
    FOREIGN KEY (codice_fiscale) REFERENCES dipendenti(codice_fiscale)
);